server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://34.31.48.154:3306/fondevi
    username: fondeviUser
    password: $7vL1rI~Z{g'm@HC
    name: fondevi

  jpa:
    hibernate:
#      ddl-auto: update

  cloud:
    gcp:
      sql:
        enabled: false
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

